// Generated by CoffeeScript 1.9.1
(function() {
  var app, express, hbs, http;

  http = require('http');

  hbs = require('hbs');

  express = require('express');

  app = express();

  app.set('view engine', 'html');

  app.engine('html', hbs.__express);

  app.get('/', function(req, res) {
    return res.render('example');
  });

  app.use("/javascripts", express["static"](__dirname + "/javascripts"));

  app.use(function(req, res, next) {
    res.redirect('/');
    return next();
  });

  app.listen(4000);

}).call(this);
