// Generated by CoffeeScript 1.9.0
(function() {
  var arrayContains, chemin, dataToArray, firstLine, firstLineHeader, firstLineHeaderJSON, fs, header200, header404, html, httpRequest, isEmpty, net, options, path, root, server;

  fs = require('fs');

  net = require('net');

  path = require('path');

  root = __dirname + '/webroot';

  httpRequest = "GET / HTTP/1.0\r\n Host: patrice:3333\r\n Connection: keep-alive\r\n Cache-Control: max-age=0\r\n Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\n User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/40.0.2214.111 Chrome/40.0.2214.111 Safari/537.36\r\n Accept-Encoding: gzip, deflate, sdch\r\n Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4\r\n";

  header200 = "HTTP/1.0 200 header \n" + "Content-Type: text/html\n";

  header404 = "HTTP/1.0 404 badRequest \n" + "Content-Type: text/html\n";

  html = "<!DOCTYPE html> <html> <head> <title>Webserver Test</title> <meta charset='utf-8'> </head> <body> Ceci est le body </body> </html>";

  options = {
    allowHalfOpen: false,
    pauseOnConnect: false
  };

  firstLineHeader = function(data) {
    var array, firstLineHeaderArray, firstLineHeaderToJSON;
    array = dataToArray(data);
    firstLineHeaderArray = array[0];
    firstLineHeaderToJSON = {
      method: firstLineHeaderArray[0],
      path: firstLineHeaderArray.length === 3 ? firstLineHeaderArray[1] : null,
      protocol: firstLineHeaderArray.length === 3 ? firstLineHeaderArray[2] : firstLineHeaderArray[1]
    };
    return firstLineHeaderToJSON;
  };

  isEmpty = function(element) {
    return !(element === '');
  };

  dataToArray = function(data) {
    var array, i, _i, _ref;
    array = data.toString().split("\r\n");
    array = array.filter(isEmpty);
    for (i = _i = 0, _ref = array.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      array[i] = array[i].split(" ");
    }
    return array;
  };

  firstLine = function(array) {
    return array[0];
  };

  arrayContains = function(array, data) {
    var value, _i, _len;
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      value = array[_i];
      if (value === data) {
        return true;
      }
    }
    return false;
  };

  firstLineHeaderJSON = firstLineHeader(httpRequest);

  console.log('firstLineHeaderJSON', firstLineHeaderJSON);

  chemin = firstLineHeaderJSON['path'];

  chemin = chemin === '/' ? 'index.html' : chemin;

  console.log('path : ', chemin);

  server = net.createServer(options, function(socket) {
    var closeSocket, connectSocket, connectionSocket, dataSocket, errorSocket;
    socket.on('connection', connectionSocket = function() {
      return console.log('socket : connection' + socket.remoteAddress(+':' + socket.remotePort + "\n"));
    });
    socket.on('connect', connectSocket = function() {
      return console.log('socket : connect');
    });
    socket.on('data', dataSocket = function(data) {
      var filePath, readStream;
      firstLineHeaderJSON = firstLineHeader(data);
      chemin = firstLineHeaderJSON['path'];
      chemin = chemin === '/' ? 'index.html' : chemin;
      filePath = path.join(root, chemin);
      console.log('search ', filePath);
      readStream = fs.createReadStream(filePath);
      socket.write(header200);
      socket.write('\r\n');
      socket.write('\r\n');
      readStream.on('open', function() {
        console.log('readStream ouvert');
        return readStream.pipe(socket);
      });
      return readStream.on('close', function() {
        return console.log('readStream close');
      });
    });
    socket.on('error', errorSocket = function() {
      return console.log('socket : error');
    });
    return socket.on('close', closeSocket = function() {
      return console.log('socket : close');
    });
  });

  server.listen(3333, 'patrice');

}).call(this);
